"""
Compare two manifests generated by make_manifest.py and report mismatches.

Usage:
  python datagen/utilities/compare_manifest.py --old manifest_old.csv --new manifest_new.csv
"""
import argparse
import pandas as pd


def compare(old_path: str, new_path: str):
    old = pd.read_csv(old_path)
    new = pd.read_csv(new_path)
    # Drop explicit num_nodes entries if they appear as a key to reduce noise
    old = old[old["key"] != "num_nodes"]
    new = new[new["key"] != "num_nodes"]

    # Keyed by (stem, key)
    old_idx = old.set_index(["stem", "key"])
    new_idx = new.set_index(["stem", "key"])

    missing_in_new = old_idx.index.difference(new_idx.index)
    missing_in_old = new_idx.index.difference(old_idx.index)

    mismatches = []
    common_idx = old_idx.index.intersection(new_idx.index)
    for idx in common_idx:
        o = old_idx.loc[idx]
        n = new_idx.loc[idx]
        def eq(a, b):
            if pd.isna(a) and pd.isna(b):
                return True
            return a == b
        if not (eq(o["dtype"], n["dtype"]) and eq(o["shape"], n["shape"]) and eq(o["sha256"], n["sha256"]) and eq(o["num_nodes"], n["num_nodes"])):
            mismatches.append((idx, o.to_dict(), n.to_dict()))

    return missing_in_new, missing_in_old, mismatches


def main(args):
    missing_in_new, missing_in_old, mismatches = compare(args.old, args.new)
    if len(missing_in_new) > 0:
        print(f"Missing in new ({len(missing_in_new)}): {list(missing_in_new[:5])}")
    if len(missing_in_old) > 0:
        print(f"Missing in old ({len(missing_in_old)}): {list(missing_in_old[:5])}")
    if mismatches:
        print(f"Mismatches: {len(mismatches)}")
        for i, (idx, o, n) in enumerate(mismatches[:10], 1):
            print(f"{i}. {idx}: old={o}, new={n}")
    else:
        print("No dtype/shape/hash/num_nodes mismatches on common keys.")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Compare manifests from make_manifest.py")
    ap.add_argument("--old", required=True, help="Manifest CSV from old env")
    ap.add_argument("--new", required=True, help="Manifest CSV from new env")
    args = ap.parse_args()
    main(args)
